name: prep-shot
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.*
  - scipy=1.10.*
  - pandas=1.5.*
  - xarray=2023.7.0
  - netcdf4
  - h5netcdf
  - h5py
  - dask
  - matplotlib
  - seaborn
  - scikit-learn
  - pyomo=6.4.*
  - openpyxl
  - xlsxwriter
  - tqdm
  - joblib
  - pytz
  - python-dateutil
  - pip
  - pip:
      - PyOptInterface==0.2.5
      - highsbox==1.7.0
      - gurobipy==10.0.2
